[package]
name = "email-worker"
version = "0.1.0"
edition = "2024"

[dependencies]
messaging = { path = "../messaging" }
store = { path = "../store" }
tokio = { version = "1", features = ["full"] }
lettre = { version = "0.11", default-features = false, features = ["smtp-transport", "tokio1-rustls-tls", "builder"] }
dotenvy = "0.15"
